version: "3.9"
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: go run main.go
